apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-deployment
  namespace: dotnet-micro-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo
  template:
    metadata:
      labels:
        app: geo
    spec:
      containers:
        - name: geo
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-geo-rest:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: geo
  namespace: dotnet-micro-rest
spec:
  selector:
    app: geo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80