apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  namespace: dotnet-micro-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-profile-rest:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: dotnet-micro-rest
spec:
  selector:
    app: profile
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80