apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: dotnet-micro-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-search-rest:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: dotnet-micro-rest
spec:
  selector:
    app: search
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80