apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-deployment
  namespace: go-micro-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo
  template:
    metadata:
      labels:
        app: geo
    spec:
      containers:
        - name: geo
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/go-geo-rest:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: geo
  namespace: go-micro-rest
spec:
  selector:
    app: geo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080