apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-mono-deployment
  namespace: python-mono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-mono
  template:
    metadata:
      labels:
        app: python-mono
    spec:
      containers:
        - name: python-mono
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/python-mono:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-mono
  namespace: python-mono
spec:
  selector:
    app: python-mono
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080