apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-deployment
  namespace: java-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate
  template:
    metadata:
      labels:
        app: rate
    spec:
      containers:
        - name: rate
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-rate-grpc:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rate
  namespace: java-micro
spec:
  selector:
    app: rate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080