apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: java-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/java-search-grpc:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: java-micro
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080