apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-mono-deployment
  namespace: dotnet-mono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-mono
  template:
    metadata:
      labels:
        app: dotnet-mono
    spec:
      containers:
        - name: dotnet-mono
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-mono:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-mono
  namespace: dotnet-mono
spec:
  selector:
    app: dotnet-mono
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80