apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: go-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-gateway
  template:
    metadata:
      labels:
        app: go-gateway
    spec:
      containers:
        - name: go-gateway
          image: ghcr.io/microservices-benchmarking-11-kiop-2023/go-gateway:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-gateway
  namespace: go-micro
spec:
  selector:
    app: go-gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080